version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    restart: unless-stopped
    build: ./backend
    command: >
      sh -c "
      pip install -r requirements.txt &&
      python manage.py makemigrations users &&
      python manage.py migrate users &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      daphne transcendence_backend.asgi:application --bind 0.0.0.0 --port 8000
      "
    volumes:
      - ./backend:/code
      - ./media:/code/media # 미디어 파일을 위한 볼륨 추가
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SETTINGS_MODULE=transcendence_backend.settings
      - PYTHONPATH=/code

  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./frontend/static/html:/usr/share/nginx/html
      - ./frontend/static/images:/usr/share/nginx/images
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./media:/usr/share/nginx/media # 미디어 파일을 위한 볼륨 추가

